### PR TITLE
Daemon SonarCloud

### PR DESCRIPTION
**Pull request by cartoon-face**
## Additions
* CRYPTONOTE_NAME has been changed to BLOCKCHAIN_DIR as the main reason this is used is to name the blockchain folder when the daemon is launched
* CCX_RELEASE_VERSION + CCX_WALLET_RELEASE_VERSION additions to form a string saying `"Conceal (or wallet) v" + version + (ID)` I.E `"Conceal v6.6.1 (Ataegina)"`
* `print_genesis_tx_hex()` will now only print a random hash, the user who is using this command should know what to do with it, we're not here to teach
* made use of 2 already implemented functions, `print_bci` and `print_bc_outs <file_name>`
* made use of `&args` in every command by using it for usage checks
* added debugging logging on commands (and functions in this file), maybe they'll prove useful

## Removals
* remove commented code
* remove timestamps and log level from client, keep them to the log file
* removed `renameDataDir()` as I think this comes from the cryptonote era as as far as i know, conceal has never been called anything different
* removed all previous calls of `std::cout` to respectively run whatever string through the logger

## Ways to Test
1) How does the Conceal version look when you load the daemon?
  * It should look like: `Conceal v6.6.1 (Ataegina)`.
  * **Please report anything different.**
2) What does the commands `print_bci` and `print_bc_outs <file_name>` do?
  * `print_bci` should print out the current blockchain height.
  * `print_bc_outs` should print out the outputs in the current block.
  * **Please report anything different.**
3) Does everything logged on screen get logged in `conceald.log` folder?
  * **Please report if not.**
4) What happens if you try and use an *arg* where one is not needed?
  * The daemon should inform you of the proper usage for all commands.
  * **Please report anything different.**
5) Are the client changes regarding removing the timestamps and log level good?
  * In terms of looks, it works how `concealwallet` works.
  * **(Yes/No)**

### CODE REVIEW

**Review by krypt0x — DISMISSED** [review]
Everything seems fine. Thank you

**Comment by cartoon-face** [comment]
I've updated the logic behind the `print_bci` and turned this into a boolean. If set true, it will print all block index's from 0 to the current, else if set to false it will only print the current id and height.

For the purpose of this daemon command, it has been set to false as we don't want to overload the daemon with this one request. A fully synced chain would print over 900k+ of block ids. The logic has been changed to still be able to do that just in case it is ever needed in the future.

I've also upstreamed this commit to include the recent work from the development branch. Should be good to go.

**Review by AxVultis — COMMENTED** [review]
Great job

**Comment by krypt0x** [comment]
What's the status of this PR?

**Comment by cartoon-face** [comment]
> What's the status of this PR?

Just need to make sure `print_as_json` is printing the correct information. I have reverted the changes regarding this function so that should work like it used to.

**Review by krypt0x — COMMENTED** [review]
It's failing on build checks. I'm afraid this PR needs to be rebased with development branch again.

**Comment by mainzerp** [comment]
1. Looks like Conceal v6.6.1 (Ataegina) - Yes
2. `print_bci` works fine now. 
    `print_bc_outs test.txt` prints "Unknown command: print_bc_outs".
3. User commands doesn't log to conceald.log.
4. Using unecessary arg `print_cn 4`: 11:55:51.049590 ERROR Usage: "print_cn".
5. Looks and works like concealwallet - Yes

**Review by krypt0x — APPROVED** [review]
Everything seems alright on my side

**Pull request merged**
